package drools.rules;

import bsep.sc.SiemCenter.model.Log;
import bsep.sc.SiemCenter.model.Alarm;
import java.util.Date;

rule "Test cep rule"
    no-loop true
    enabled true
    timer(cron:0/5 * * * * ?)
    when
        $log1: Log($src: machineIp)
        not ( Alarm(machineSource == $src) )
        Number(intValue >= 5) from accumulate(
            $log2: Log(
                this != $log1,
                machineIp == $src
            ) over window:time(1m),
            count($log2)
        )
    then
        System.out.println("Rule name");
        insert(new Alarm());
end
