package drools.rules;

import bsep.sc.SiemCenter.events.LogEvent;
import bsep.sc.SiemCenter.events.Alarm;
import bsep.sc.SiemCenter.events.AlarmType;
import java.util.Date;

rule "*ENTER_NAME*"
    no-loop true
    enabled true
    when
        $log1: LogEvent($src: machineSource, *ADD CONDITION*)
        not ( Alarm(machineSource == $src) )
        Number(intValue >= 5) from accumulate(
            $log2: LogEvent(
                this != $log1,
                *ADD CONDITION*
            ) over window:time(1m),
            count($log2)
        )
    then
        System.out.println("Rule name")
        insert(new Alarm());
end
