package drools.rules;

import bsep.sc.SiemCenter.events.LogEvent;
import bsep.sc.SiemCenter.events.Alarm;
import bsep.sc.SiemCenter.events.AlarmType;
import java.util.Date;

rule "Test simple rule"
    no-loop true
    enabled true
    when
        $log1: LogEvent($src: machineSource)
        not ( Alarm(machineSource == $src) )
    then
        System.out.println("Rule name");
        insert(new Alarm());
end
